//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Don_Hang()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
            this.Van_Chuyen = new HashSet<Van_Chuyen>();
        }
    
        public string Ma_don_hang { get; set; }
        public string Ma_nguoi_dung { get; set; }
        public string Ma_dia_chi { get; set; }
        public Nullable<System.DateTime> Ngay_dat_hang { get; set; }
        public string Trang_thai_don_hang { get; set; }
        public string Phuong_thuc_thanh_toan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Dia_Chi Dia_Chi { get; set; }
        public virtual Nguoi_Dung Nguoi_Dung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Van_Chuyen> Van_Chuyen { get; set; }
    }
}
