//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho_Hang
    {
        public string Ma_kho { get; set; }
        public string Ma_dia_chi { get; set; }
    
        public virtual Dia_Chi Dia_Chi { get; set; }
    }
}
