//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_Dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoi_Dung()
        {
            this.Don_Hang = new HashSet<Don_Hang>();
            this.Phieu_Nhap_Kho = new HashSet<Phieu_Nhap_Kho>();
            this.Tai_Khoan = new HashSet<Tai_Khoan>();
            this.Dia_Chi = new HashSet<Dia_Chi>();
            this.Vai_Tro = new HashSet<Vai_Tro>();
        }
    
        public string Ma_nguoi_dung { get; set; }
        public string Ho_va_ten { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Hang> Don_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieu_Nhap_Kho> Phieu_Nhap_Kho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tai_Khoan> Tai_Khoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dia_Chi> Dia_Chi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vai_Tro> Vai_Tro { get; set; }
    }
}
