//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tai_Khoan
    {
        public string Tai_khoan1 { get; set; }
        public string Ma_nguoi_dung { get; set; }
        public string Mat_khau { get; set; }
    
        public virtual Nguoi_Dung Nguoi_Dung { get; set; }
    }
}
