//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public string Ma_gio_hang { get; set; }
        public string Ma_san_pham { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Gio_hang Gio_hang { get; set; }
        public virtual San_Pham San_Pham { get; set; }
    }
}
