//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Phieu_Nhap
    {
        public string Ma_ctpn { get; set; }
        public string Ma_phieu { get; set; }
        public string Ma_san_pham { get; set; }
        public Nullable<int> So_luong { get; set; }
        public string Gia_nhap { get; set; }
        public string Thanh_tien { get; set; }
    
        public virtual Phieu_Nhap_Kho Phieu_Nhap_Kho { get; set; }
        public virtual San_Pham San_Pham { get; set; }
    }
}
