//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia_Chi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dia_Chi()
        {
            this.Don_Hang = new HashSet<Don_Hang>();
            this.Kho_Hang = new HashSet<Kho_Hang>();
            this.Nha_Cung_Cap = new HashSet<Nha_Cung_Cap>();
            this.Nguoi_Dung = new HashSet<Nguoi_Dung>();
        }
    
        public string Ma_dia_chi { get; set; }
        public string Tinh_ThanhPho { get; set; }
        public string Quan_Huyen { get; set; }
        public string Xa_Phuong { get; set; }
        public string Duong { get; set; }
        public Nullable<int> So_nha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Hang> Don_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kho_Hang> Kho_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nha_Cung_Cap> Nha_Cung_Cap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nguoi_Dung> Nguoi_Dung { get; set; }
    }
}
