//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_Dung
    {
        public string Ma_nguoi_dung { get; set; }
        public string Ho_va_ten { get; set; }
        public string Ma_vai_tro { get; set; }
        public string password { get; set; }
        public bool Gioi_tinh { get; set; }
    
        public virtual Vai_Tro Vai_Tro { get; set; }
    }
}
