//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_Dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoi_Dung()
        {
            this.Don_Hang = new HashSet<Don_Hang>();
            this.Gio_hang = new HashSet<Gio_hang>();
            this.nguoiDung_diaChi = new HashSet<nguoiDung_diaChi>();
            this.Phieu_Nhap_Kho = new HashSet<Phieu_Nhap_Kho>();
        }
    
        public string Ma_nguoi_dung { get; set; }
        public string Ho_va_ten { get; set; }
        public string Ma_vai_tro { get; set; }
        public string password { get; set; }
        public bool Gioi_tinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Hang> Don_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gio_hang> Gio_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nguoiDung_diaChi> nguoiDung_diaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieu_Nhap_Kho> Phieu_Nhap_Kho { get; set; }
        public virtual Vai_Tro Vai_Tro { get; set; }
    }
}
