//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Van_Chuyen
    {
        public string Ma_van_don { get; set; }
        public string Ma_don_hang { get; set; }
        public Nullable<System.DateTime> Ngay_bat_dau { get; set; }
        public Nullable<System.DateTime> Ngay_du_kien { get; set; }
        public string Phi_van_chuyen { get; set; }
        public string Ghi_chu { get; set; }
    
        public virtual Don_Hang Don_Hang { get; set; }
    }
}
